// <auto-generated />
using Interview_Schedule_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview_Schedule_Management.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220820053557_LIKKI")]
    partial class LIKKI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Interview_Schedule_Management.Models.Admin", b =>
                {
                    b.Property<int>("AD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AD_ID"), 1L, 1);

                    b.Property<string>("AD_Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AD_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AD_Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AD_ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Interview_Schedule_Management.Models.AspirantApplication", b =>
                {
                    b.Property<int>("APP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("APP_ID"), 1L, 1);

                    b.Property<int>("APP_C_ID")
                        .HasColumnType("int");

                    b.Property<int>("APP_EXP")
                        .HasColumnType("int");

                    b.Property<string>("APP_INT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_QUALI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("APP_REFF_ID")
                        .HasColumnType("int");

                    b.Property<bool>("INT_HR_MARKS")
                        .HasColumnType("bit");

                    b.Property<bool>("INT_STAT")
                        .HasColumnType("bit");

                    b.HasKey("APP_ID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Interview_Schedule_Management.Models.Candidate", b =>
                {
                    b.Property<int>("C_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_ID"), 1L, 1);

                    b.Property<string>("C_AGENT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_DOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_FNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_GENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_LNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C_ID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Interview_Schedule_Management.Models.Job", b =>
                {
                    b.Property<int>("JOB_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JOB_ID"), 1L, 1);

                    b.Property<string>("CLOSING_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPANY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOMAIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HR_ID")
                        .HasColumnType("int");

                    b.Property<string>("INT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIORITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("REQ_EXP")
                        .HasColumnType("int");

                    b.Property<string>("REQ_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("REQ_VAC")
                        .HasColumnType("int");

                    b.HasKey("JOB_ID");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
